### ISSUE TITLE
Can't register item tag and then use it in recipe

### ISSUE THREAD

**Issue by Reoseah** [swordglowsblue/artifice#2]
e.g. 
```
data.addItemTag(new Identifier("c", "iron_ingot"), 
        tag -> tag.value(new Identifier("minecraft:iron_ingot")));
data.addSmeltingRecipe(new Identifier(modid, "example"), recipe -> {
    recipe.ingredientTag(new Identifier("c", "iron_ingot"));
    recipe.result(new Identifier("minecraft", "diamond"));
    recipe.experience(0);
    recipe.cookingTime(200);
});
```
expected: smelting iron ingot gives diamond, custom ingots can be added to that tag
what happens:
recipes give errors similar to this one when entering world
```
[08:46:23] [Server thread/ERROR]: Parsing error loading recipe operatingpower:diamond_dust_from_ore
com.google.gson.JsonSyntaxException: Unknown item tag 'c:diamond_ore'
	at net.minecraft.recipe.Ingredient.entryFromJson(Ingredient.java:200) ~[minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.recipe.Ingredient.fromJson(Ingredient.java:167) ~[minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at operatingpower.recipe.MachineRecipeSerializer.read(MachineRecipeSerializer.java:39) ~[main/:?]
	at operatingpower.recipe.MachineRecipeSerializer.read(MachineRecipeSerializer.java:1) ~[main/:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager.java:164) ~[minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager.java:66) ~[minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.resource.SynchronousResourceReloadListener.method_18235(SynchronousResourceReloadListener.java:10) ~[minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:783) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478) ~[?:?]
	at net.minecraft.resource.ResourceReloader.method_18365(ResourceReloader.java:69) ~[minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.ServerTask.run(ServerTask.java:17) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.util.ThreadExecutor.runSafely(ThreadExecutor.java:127) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.util.NonBlockingThreadExecutor.runSafely(NonBlockingThreadExecutor.java:22) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.util.ThreadExecutor.executeQueuedTask(ThreadExecutor.java:105) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:695) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.MinecraftServer.executeQueuedTask(MinecraftServer.java:689) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.util.ThreadExecutor.waitFor(ThreadExecutor.java:115) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.MinecraftServer.reloadDataPacks(MinecraftServer.java:1443) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.MinecraftServer.loadWorldDataPacks(MinecraftServer.java:432) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.loadWorld(IntegratedServer.java:75) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.integrated.IntegratedServer.setupServer(IntegratedServer.java:94) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:603) [minecraft-1.14.2-mapped-net.fabricmc.yarn-7.jar:?]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by Reoseah** [comment]
oh wait, I have forget to delete json recipes... so it seems none of artifice-registered recipes with artifice-registered tags work

**Comment by swordglowsblue** [comment]
Could you use the `ArtificeResourcePack#dumpResources` method to output the JSON being created by Artifice and post the relevant tag and recipe files please? I'd like to see what's being created. My testing on the data side has been a little lackluster, so it's not unlikely that I made a mistake in how I set the builders up.

**Comment by Reoseah** [comment]
oh, yeah, that's not the way it should be
![Capture](https://user-images.githubusercontent.com/20323084/59824277-f33bb300-9330-11e9-9002-d1557f8f87d1.PNG)

**Comment by Reoseah** [comment]
I think I see what causes it
https://github.com/swordglowsblue/artifice/blob/6a9d32723f126038b6e1f49e0cd7bba1dbe90837/src/main/java/com/swordglowsblue/artifice/impl/ArtificeResourcePackImpl.java#L124
https://github.com/swordglowsblue/artifice/blob/6a9d32723f126038b6e1f49e0cd7bba1dbe90837/src/main/java/com/swordglowsblue/artifice/impl/ArtificeResourcePackImpl.java#L133
probably should be "recipes/" with slash at the end too

**Comment by swordglowsblue** [comment]
You are absolutely right and it probably would have taken me hours to catch that =) Thanks!

**Comment by Reoseah** [comment]
Item tags still don't work. Still same errors while loading recipes, also tried this
```java
ItemTags.getContainer().getEntries().forEach((id, item) -> {
			System.out.println(id + " " + item.toJson(Registry.ITEM::getId));
		});
```
and output doesn't have any of tags I added with artifice:
<details><p>
<summary>output</summary>

```
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:banners {"replace":false,"values":["minecraft:white_banner","minecraft:orange_banner","minecraft:magenta_banner","minecraft:light_blue_banner","minecraft:yellow_banner","minecraft:lime_banner","minecraft:pink_banner","minecraft:gray_banner","minecraft:light_gray_banner","minecraft:cyan_banner","minecraft:purple_banner","minecraft:blue_banner","minecraft:brown_banner","minecraft:green_banner","minecraft:red_banner","minecraft:black_banner"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:trapdoors {"replace":false,"values":["#minecraft:wooden_trapdoors","minecraft:iron_trapdoor"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_fences {"replace":false,"values":["minecraft:oak_fence","minecraft:acacia_fence","minecraft:dark_oak_fence","minecraft:spruce_fence","minecraft:birch_fence","minecraft:jungle_fence"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:buttons {"replace":false,"values":["#minecraft:wooden_buttons","minecraft:stone_button"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_slabs {"replace":false,"values":["minecraft:oak_slab","minecraft:spruce_slab","minecraft:birch_slab","minecraft:jungle_slab","minecraft:acacia_slab","minecraft:dark_oak_slab"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: fabric:swords {"replace":false,"values":["minecraft:wooden_sword","minecraft:stone_sword","minecraft:iron_sword","minecraft:golden_sword","minecraft:diamond_sword"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:planks {"replace":false,"values":["minecraft:oak_planks","minecraft:spruce_planks","minecraft:birch_planks","minecraft:jungle_planks","minecraft:acacia_planks","minecraft:dark_oak_planks"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:boats {"replace":false,"values":["minecraft:oak_boat","minecraft:spruce_boat","minecraft:birch_boat","minecraft:jungle_boat","minecraft:acacia_boat","minecraft:dark_oak_boat"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:small_flowers {"replace":false,"values":["minecraft:dandelion","minecraft:poppy","minecraft:blue_orchid","minecraft:allium","minecraft:azure_bluet","minecraft:red_tulip","minecraft:orange_tulip","minecraft:white_tulip","minecraft:pink_tulip","minecraft:oxeye_daisy","minecraft:cornflower","minecraft:lily_of_the_valley","minecraft:wither_rose"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: fabric:pickaxes {"replace":false,"values":["minecraft:wooden_pickaxe","minecraft:stone_pickaxe","minecraft:iron_pickaxe","minecraft:golden_pickaxe","minecraft:diamond_pickaxe"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:dark_oak_logs {"replace":false,"values":["minecraft:dark_oak_log","minecraft:dark_oak_wood","minecraft:stripped_dark_oak_log","minecraft:stripped_dark_oak_wood"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:rails {"replace":false,"values":["minecraft:rail","minecraft:powered_rail","minecraft:detector_rail","minecraft:activator_rail"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_trapdoors {"replace":false,"values":["minecraft:acacia_trapdoor","minecraft:birch_trapdoor","minecraft:dark_oak_trapdoor","minecraft:jungle_trapdoor","minecraft:oak_trapdoor","minecraft:spruce_trapdoor"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:leaves {"replace":false,"values":["minecraft:jungle_leaves","minecraft:oak_leaves","minecraft:spruce_leaves","minecraft:dark_oak_leaves","minecraft:acacia_leaves","minecraft:birch_leaves"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:walls {"replace":false,"values":["minecraft:cobblestone_wall","minecraft:mossy_cobblestone_wall","minecraft:brick_wall","minecraft:prismarine_wall","minecraft:red_sandstone_wall","minecraft:mossy_stone_brick_wall","minecraft:granite_wall","minecraft:stone_brick_wall","minecraft:nether_brick_wall","minecraft:andesite_wall","minecraft:red_nether_brick_wall","minecraft:sandstone_wall","minecraft:end_stone_brick_wall","minecraft:diorite_wall"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:coals {"replace":false,"values":["minecraft:coal","minecraft:charcoal"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:jungle_logs {"replace":false,"values":["minecraft:jungle_log","minecraft:jungle_wood","minecraft:stripped_jungle_log","minecraft:stripped_jungle_wood"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_stairs {"replace":false,"values":["minecraft:oak_stairs","minecraft:spruce_stairs","minecraft:birch_stairs","minecraft:jungle_stairs","minecraft:acacia_stairs","minecraft:dark_oak_stairs"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:spruce_logs {"replace":false,"values":["minecraft:spruce_log","minecraft:spruce_wood","minecraft:stripped_spruce_log","minecraft:stripped_spruce_wood"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:signs {"replace":false,"values":["minecraft:oak_sign","minecraft:spruce_sign","minecraft:birch_sign","minecraft:acacia_sign","minecraft:jungle_sign","minecraft:dark_oak_sign"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_pressure_plates {"replace":false,"values":["minecraft:oak_pressure_plate","minecraft:spruce_pressure_plate","minecraft:birch_pressure_plate","minecraft:jungle_pressure_plate","minecraft:acacia_pressure_plate","minecraft:dark_oak_pressure_plate"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:carpets {"replace":false,"values":["minecraft:white_carpet","minecraft:orange_carpet","minecraft:magenta_carpet","minecraft:light_blue_carpet","minecraft:yellow_carpet","minecraft:lime_carpet","minecraft:pink_carpet","minecraft:gray_carpet","minecraft:light_gray_carpet","minecraft:cyan_carpet","minecraft:purple_carpet","minecraft:blue_carpet","minecraft:brown_carpet","minecraft:green_carpet","minecraft:red_carpet","minecraft:black_carpet"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wool {"replace":false,"values":["minecraft:white_wool","minecraft:orange_wool","minecraft:magenta_wool","minecraft:light_blue_wool","minecraft:yellow_wool","minecraft:lime_wool","minecraft:pink_wool","minecraft:gray_wool","minecraft:light_gray_wool","minecraft:cyan_wool","minecraft:purple_wool","minecraft:blue_wool","minecraft:brown_wool","minecraft:green_wool","minecraft:red_wool","minecraft:black_wool"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_buttons {"replace":false,"values":["minecraft:oak_button","minecraft:spruce_button","minecraft:birch_button","minecraft:jungle_button","minecraft:acacia_button","minecraft:dark_oak_button"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:acacia_logs {"replace":false,"values":["minecraft:acacia_log","minecraft:acacia_wood","minecraft:stripped_acacia_log","minecraft:stripped_acacia_wood"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:stairs {"replace":false,"values":["minecraft:oak_stairs","minecraft:cobblestone_stairs","minecraft:spruce_stairs","minecraft:sandstone_stairs","minecraft:acacia_stairs","minecraft:jungle_stairs","minecraft:birch_stairs","minecraft:dark_oak_stairs","minecraft:nether_brick_stairs","minecraft:stone_brick_stairs","minecraft:brick_stairs","minecraft:purpur_stairs","minecraft:quartz_stairs","minecraft:red_sandstone_stairs","minecraft:prismarine_brick_stairs","minecraft:prismarine_stairs","minecraft:dark_prismarine_stairs","minecraft:polished_granite_stairs","minecraft:smooth_red_sandstone_stairs","minecraft:mossy_stone_brick_stairs","minecraft:polished_diorite_stairs","minecraft:mossy_cobblestone_stairs","minecraft:end_stone_brick_stairs","minecraft:stone_stairs","minecraft:smooth_sandstone_stairs","minecraft:smooth_quartz_stairs","minecraft:granite_stairs","minecraft:andesite_stairs","minecraft:red_nether_brick_stairs","minecraft:polished_andesite_stairs","minecraft:diorite_stairs"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:music_discs {"replace":false,"values":["minecraft:music_disc_13","minecraft:music_disc_cat","minecraft:music_disc_blocks","minecraft:music_disc_chirp","minecraft:music_disc_far","minecraft:music_disc_mall","minecraft:music_disc_mellohi","minecraft:music_disc_stal","minecraft:music_disc_strad","minecraft:music_disc_ward","minecraft:music_disc_11","minecraft:music_disc_wait"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:fishes {"replace":false,"values":["minecraft:cod","minecraft:cooked_cod","minecraft:salmon","minecraft:cooked_salmon","minecraft:pufferfish","minecraft:tropical_fish"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:anvil {"replace":false,"values":["minecraft:anvil","minecraft:chipped_anvil","minecraft:damaged_anvil"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:birch_logs {"replace":false,"values":["minecraft:birch_log","minecraft:birch_wood","minecraft:stripped_birch_log","minecraft:stripped_birch_wood"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:logs {"replace":false,"values":["#minecraft:dark_oak_logs","#minecraft:oak_logs","#minecraft:acacia_logs","#minecraft:birch_logs","#minecraft:jungle_logs","#minecraft:spruce_logs"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:stone_bricks {"replace":false,"values":["minecraft:stone_bricks","minecraft:mossy_stone_bricks","minecraft:cracked_stone_bricks","minecraft:chiseled_stone_bricks"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: fabric:axes {"replace":false,"values":["minecraft:wooden_axe","minecraft:stone_axe","minecraft:iron_axe","minecraft:golden_axe","minecraft:diamond_axe"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:arrows {"replace":false,"values":["minecraft:arrow","minecraft:tipped_arrow","minecraft:spectral_arrow"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:sand {"replace":false,"values":["minecraft:sand","minecraft:red_sand"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: operatingpower:diamond_or_dust {"replace":false,"values":["minecraft:diamond","operatingpower:diamond_dust"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:slabs {"replace":false,"values":["minecraft:stone_slab","minecraft:smooth_stone_slab","minecraft:stone_brick_slab","minecraft:sandstone_slab","minecraft:acacia_slab","minecraft:birch_slab","minecraft:dark_oak_slab","minecraft:jungle_slab","minecraft:oak_slab","minecraft:spruce_slab","minecraft:purpur_slab","minecraft:quartz_slab","minecraft:red_sandstone_slab","minecraft:brick_slab","minecraft:cobblestone_slab","minecraft:nether_brick_slab","minecraft:petrified_oak_slab","minecraft:prismarine_slab","minecraft:prismarine_brick_slab","minecraft:dark_prismarine_slab","minecraft:polished_granite_slab","minecraft:smooth_red_sandstone_slab","minecraft:mossy_stone_brick_slab","minecraft:polished_diorite_slab","minecraft:mossy_cobblestone_slab","minecraft:end_stone_brick_slab","minecraft:smooth_sandstone_slab","minecraft:smooth_quartz_slab","minecraft:granite_slab","minecraft:andesite_slab","minecraft:red_nether_brick_slab","minecraft:polished_andesite_slab","minecraft:diorite_slab","minecraft:cut_sandstone_slab","minecraft:cut_red_sandstone_slab"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:fences {"replace":false,"values":["#minecraft:wooden_fences","minecraft:nether_brick_fence"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:wooden_doors {"replace":false,"values":["minecraft:oak_door","minecraft:spruce_door","minecraft:birch_door","minecraft:jungle_door","minecraft:acacia_door","minecraft:dark_oak_door"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:saplings {"replace":false,"values":["minecraft:oak_sapling","minecraft:spruce_sapling","minecraft:birch_sapling","minecraft:jungle_sapling","minecraft:acacia_sapling","minecraft:dark_oak_sapling"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:beds {"replace":false,"values":["minecraft:red_bed","minecraft:black_bed","minecraft:blue_bed","minecraft:brown_bed","minecraft:cyan_bed","minecraft:gray_bed","minecraft:green_bed","minecraft:light_blue_bed","minecraft:light_gray_bed","minecraft:lime_bed","minecraft:magenta_bed","minecraft:orange_bed","minecraft:pink_bed","minecraft:purple_bed","minecraft:white_bed","minecraft:yellow_bed"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:oak_logs {"replace":false,"values":["minecraft:oak_log","minecraft:oak_wood","minecraft:stripped_oak_log","minecraft:stripped_oak_wood"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: fabric:hoes {"replace":false,"values":["minecraft:wooden_hoe","minecraft:stone_hoe","minecraft:iron_hoe","minecraft:golden_hoe","minecraft:diamond_hoe"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: minecraft:doors {"replace":false,"values":["#minecraft:wooden_doors","minecraft:iron_door"]}
[10:07:33] [Server thread/INFO]: [STDOUT]: fabric:shovels {"replace":false,"values":["minecraft:wooden_shovel","minecraft:stone_shovel","minecraft:iron_shovel","minecraft:golden_shovel","minecraft:diamond_shovel"]}
```

</p></details>

**Comment by swordglowsblue** [comment]
I'll take another look in the morning. Could you post the JSON data contained in one of your tags and in one of the recipes that's supposed to use it please?

**Comment by Reoseah** [comment]
https://github.com/swordglowsblue/artifice/blob/6a9d32723f126038b6e1f49e0cd7bba1dbe90837/src/main/java/com/swordglowsblue/artifice/impl/ArtificeResourcePackImpl.java#L153
It seems chain of calls from ItemTags ends up calling this with `""` as second parameter

**Comment by swordglowsblue** [comment]
I need to refine a couple things about that function anyway, I'll take a look when I have time tomorrow. Hopefully it's a path resolution issue and not a load order issue or worse.

**Comment by swordglowsblue** [comment]
Alright, I've added it with that commit =) If you run across anything else, please do let me know.
